# Generated by Django 5.1.4 on 2025-03-24 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='تیتر خبر')),
                ('banner', models.ImageField(upload_to='NewsBanner/', verbose_name='تصویر اصلی')),
                ('slug', models.SlugField(verbose_name='اسلاگ')),
                ('text', models.TextField()),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
            },
        ),
    ]
