# Generated by Django 5.1.4 on 2025-03-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='datetime',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='short_info',
            field=models.CharField(default='', max_length=255, verbose_name='توضیحات کوتاه'),
        ),
    ]
