# Generated by Django 5.1.4 on 2025-03-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_module', '0002_remove_newsmodel_datetime_newsmodel_short_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
