# Generated by Django 5.1.4 on 2025-03-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_module', '0003_newsmodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال بودن خبر'),
        ),
    ]
