# Generated by Django 5.1.4 on 2025-03-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_module', '0004_alter_newsmodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='اسلاگ'),
        ),
    ]
