# Generated by Django 5.1.4 on 2025-03-27 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_module', '0005_alter_newsmodel_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='writer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
    ]
