# Generated by Django 5.1.4 on 2025-03-27 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_module', '0008_alter_newsmodel_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='writer',
        ),
    ]
