# Generated by Django 5.1.4 on 2025-03-09 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0003_tempuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': 'درآمد', 'verbose_name_plural': 'درآمد ها'},
        ),
        migrations.AlterModelOptions(
            name='spend',
            options={'verbose_name': 'خرج', 'verbose_name_plural': 'مخارج'},
        ),
        migrations.AlterModelOptions(
            name='tempuser',
            options={'verbose_name': 'کاربر موقت', 'verbose_name_plural': 'کاربران موقت'},
        ),
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name': 'توکن', 'verbose_name_plural': 'توکن ها'},
        ),
        migrations.AlterField(
            model_name='income',
            name='price',
            field=models.BigIntegerField(verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='income',
            name='time',
            field=models.DateTimeField(verbose_name='تاریخ و زمان'),
        ),
        migrations.AlterField(
            model_name='income',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='income',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='spend',
            name='price',
            field=models.BigIntegerField(verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='spend',
            name='time',
            field=models.DateTimeField(verbose_name='تاریخ و زمان'),
        ),
        migrations.AlterField(
            model_name='spend',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='spend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='date',
            field=models.DateTimeField(verbose_name='تاریخ و زمان'),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='password',
            field=models.CharField(max_length=255, verbose_name='رمز عبور'),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='random_str',
            field=models.CharField(max_length=50, verbose_name='کد فعال\u200cسازی حساب'),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='username',
            field=models.CharField(max_length=255, verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=50, verbose_name='توکن'),
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
