# Generated by Django 5.1.4 on 2025-03-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0004_alter_income_options_alter_spend_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='note',
            field=models.TextField(default='', null=True, verbose_name='یاداشت'),
        ),
        migrations.AddField(
            model_name='spend',
            name='note',
            field=models.TextField(default='', null=True, verbose_name='یاداشت'),
        ),
    ]
