# Generated by Django 5.1.4 on 2025-03-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0005_income_note_spend_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='note',
            field=models.TextField(blank=True, default='', null=True, verbose_name='یاداشت'),
        ),
        migrations.AlterField(
            model_name='spend',
            name='note',
            field=models.TextField(blank=True, default='', null=True, verbose_name='یاداشت'),
        ),
    ]
