# Generated by Django 5.1.4 on 2025-03-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0006_alter_income_note_alter_spend_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneTempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='نام کاربری')),
                ('password', models.CharField(max_length=255, verbose_name='رمز عبور')),
                ('mobile', models.EmailField(max_length=255, verbose_name='موبایل')),
                ('random_str', models.CharField(max_length=50, verbose_name='کد فعال\u200cسازی حساب')),
                ('date', models.DateTimeField(verbose_name='تاریخ و زمان')),
            ],
        ),
        migrations.RenameModel(
            old_name='TempUser',
            new_name='EmailTempUser',
        ),
    ]
