# Generated by Django 5.1.4 on 2025-03-13 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0007_phonetempuser_rename_tempuser_emailtempuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailTempUser',
            new_name='TempUser',
        ),
        migrations.DeleteModel(
            name='PhoneTempUser',
        ),
    ]
