# Generated by Django 5.1.7 on 2025-03-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spends', '0002_alter_income_time_alter_spend_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('random_str', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
