# Generated by Django 5.1.4 on 2025-03-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spends', '0008_rename_emailtempuser_tempuser_delete_phonetempuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgetPasswordUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='ایمیل')),
                ('random_str', models.CharField(max_length=50, verbose_name='کد فعال\u200cسازی حساب')),
            ],
        ),
    ]
