# Generated by Django 5.1.4 on 2025-03-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام ارسال کننده')),
                ('subject', models.CharField(max_length=255, verbose_name='موضوع پیام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل ارسال کننده')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('datetime', models.DateTimeField(verbose_name='زمان ارسال پیام')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
    ]
