# Generated by Django 5.1.4 on 2025-03-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال پیام'),
        ),
    ]
