# Generated by Django 5.1.4 on 2025-03-24 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forgetpasswordusers',
            options={'verbose_name': 'کاربران درخواست تغییر رمز'},
        ),
    ]
